# Generated by Django 4.1.3 on 2022-11-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_app', '0003_tblsuscripciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblreservacion',
            name='habitacion_id',
        ),
        migrations.RemoveField(
            model_name='tblreservacion',
            name='hora_llegada',
        ),
        migrations.RemoveField(
            model_name='tblreservacion',
            name='hora_salida',
        ),
        migrations.RemoveField(
            model_name='tblreservacion',
            name='precio_hab_id',
        ),
        migrations.AddField(
            model_name='tblreservacion',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tblreservacion',
            name='habitacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tblsuscripciones',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
