# Generated by Django 4.1.3 on 2022-11-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_app', '0005_alter_tblreservacion_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblreservacion',
            name='hotel_id',
        ),
    ]
