# Generated by Django 4.1.3 on 2022-11-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_app', '0006_remove_tblreservacion_hotel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcliente',
            name='habitacion_id',
        ),
        migrations.AddField(
            model_name='tblcliente',
            name='habitacion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
